In [1]:
# Imports
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
# Load ratings.dat
ratings = pd.read_csv(
    "../data/raw/ml-1m/ratings.dat",
    sep="::",
    engine="python",
    names=["user_id", "movie_id", "rating", "timestamp"]
)

ratings.head()

   user_id  movie_id  rating  timestamp
0        1      1193       5  978300760
1        1       661       3  978302109
2        1       914       3  978301968
3        1      3408       4  978300275
4        1      2355       5  978824291

In [3]:
# Load movies
movies = pd.read_csv(
    "../data/raw/ml-1m/movies.dat",
    sep="::",
    engine="python",
    encoding="latin-1",
    names=["movie_id", "title", "genres"]
)

movies.head()

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [4]:
# Load Users
users = pd.read_csv(
    "../data/raw/ml-1m/users.dat",
    sep="::",
    engine="python",
    names=[
        "user_id",
        "gender",
        "age",
        "occupation",
        "zip_code"
    ]
)

users.head()

   user_id gender  age  occupation zip_code
0        1      F    1          10    48067
1        2      M   56          16    70072
2        3      M   25          15    55117
3        4      M   45           7    02460
4        5      M   25          20    55455

In [5]:
# Basic dataset statistics
print("Users:", ratings["user_id"].nunique())
print("Movies:", ratings["movie_id"].nunique())
print("Interactions:", len(ratings))

Users: 6040
Movies: 3706
Interactions: 1000209

In [6]:
# Sparsity
num_users = ratings["user_id"].nunique()
num_movies = ratings["movie_id"].nunique()
num_interactions = len(ratings)

possible_interactions = num_users * num_movies

print("Possible interactions:", possible_interactions)
print("Observed interactions:", num_interactions)

sparsity = 1 - (num_interactions / possible_interactions)

print(f"Sparsity: {sparsity * 100:.2f}%")

Possible interactions: 22384240
Observed interactions: 1000209
Sparsity: 95.53%

In [7]:
# Rating distribution
ratings["rating"].value_counts().sort_index()

rating
1     56174
2    107557
3    261197
4    348971
5    226310
Name: count, dtype: int64

In [8]:
# Timestamp range
ratings["datetime"] = pd.to_datetime(
    ratings["timestamp"],
    unit="s"
)

print("Earliest:", ratings["datetime"].min())
print("Latest:", ratings["datetime"].max())

Earliest: 2000-04-25 23:05:32
Latest: 2003-02-28 17:49:50

In [9]:
# Duplicate user-movie interactions
duplicates = ratings.duplicated(
    subset=["user_id", "movie_id"]
).sum()

print("Duplicate user-movie pairs:", duplicates)

Duplicate user-movie pairs: 0

In [10]:
# User Activity
user_counts = ratings.groupby("user_id").size()

print(user_counts.describe())

movie_counts = ratings.groupby("movie_id").size()

print(movie_counts.describe())

count    6040.000000
mean      165.597517
std       192.747029
min        20.000000
25%        44.000000
50%        96.000000
75%       208.000000
max      2314.000000
dtype: float64
count    3706.000000
mean      269.889099
std       384.047838
min         1.000000
25%        33.000000
50%       123.500000
75%       350.000000
max      3428.000000
dtype: float64

In [11]:
positive_ratings = ratings[ratings["rating"] >= 4]

print("Positive interactions:", len(positive_ratings))

print(
    f"Percentage retained: "
    f"{100 * len(positive_ratings) / len(ratings):.2f}%"
)

Positive interactions: 575281
Percentage retained: 57.52%